# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\client.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(886, 849)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.chat_field_msg = QtWidgets.QTextEdit(self.tab)
        self.chat_field_msg.setGeometry(QtCore.QRect(90, 60, 661, 311))
        self.chat_field_msg.setObjectName("chat_field_msg")
        self.btn_send_msg = QtWidgets.QPushButton(self.tab)
        self.btn_send_msg.setGeometry(QtCore.QRect(620, 590, 91, 41))
        self.btn_send_msg.setObjectName("btn_send_msg")
        self.btn_send_file = QtWidgets.QPushButton(self.tab)
        self.btn_send_file.setGeometry(QtCore.QRect(520, 590, 93, 41))
        self.btn_send_file.setObjectName("btn_send_file")
        self.text_input_msg = QtWidgets.QTextEdit(self.tab)
        self.text_input_msg.setGeometry(QtCore.QRect(93, 420, 661, 101))
        self.text_input_msg.setObjectName("text_input_msg")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.chat_field_msg_2 = QtWidgets.QTextEdit(self.tab_2)
        self.chat_field_msg_2.setGeometry(QtCore.QRect(170, 80, 491, 291))
        self.chat_field_msg_2.setObjectName("chat_field_msg_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 560, 93, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_2.setGeometry(QtCore.QRect(173, 440, 491, 87))
        self.textEdit_2.setObjectName("textEdit_2")
        self.btn_send_msg_2 = QtWidgets.QPushButton(self.tab_2)
        self.btn_send_msg_2.setGeometry(QtCore.QRect(570, 560, 91, 41))
        self.btn_send_msg_2.setObjectName("btn_send_msg_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 886, 26))
        self.menubar.setObjectName("menubar")
        self.menuSet_User = QtWidgets.QMenu(self.menubar)
        self.menuSet_User.setObjectName("menuSet_User")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionLogout = QtWidgets.QAction(MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionRegister = QtWidgets.QAction(MainWindow)
        self.actionRegister.setObjectName("actionRegister")
        self.menuSet_User.addAction(self.actionLogin)
        self.menuSet_User.addAction(self.actionLogout)
        self.menuSet_User.addAction(self.actionRegister)
        self.menuSet_User.addSeparator()
        self.menubar.addAction(self.menuSet_User.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_send_msg.setText(_translate("MainWindow", "send"))
        self.btn_send_file.setText(_translate("MainWindow", "send file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Secure Chat"))
        self.pushButton_2.setText(_translate("MainWindow", "send file"))
        self.btn_send_msg_2.setText(_translate("MainWindow", "send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Collision Mode"))
        self.menuSet_User.setTitle(_translate("MainWindow", "Set User"))
        self.actionLogin.setText(_translate("MainWindow", "Login"))
        self.actionLogout.setText(_translate("MainWindow", "Logout"))
        self.actionRegister.setText(_translate("MainWindow", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
